<?php 
ini_set('display_errors', 1);
require 'emailFunction.php';


$emails = [
    "ZOE.LEE@NOW-INTERFACE.COM",
    "rsgupta@djkindia.co.in",
    "soyoung.jang@kohyoung.com",
    "ppmfg@precisionproducts.in",
    "rohitdoke@doshaheen.com",
    "mani.prasad@orbitsolutions.net",
    "mohit.singla@vvdntech.in",
    "hgr@jtcorp.co.kr",
    "marketing@surplusglobal.com",
    "r-pal@ml.tanaka.co.jp",
    "abhidha.s@deltaww.com",
    "munira.rangwala@nagase.co.in",
    "hariharasudan@stratusauto.com",
    "samy@douyee.com.sg",
    "y-murai@ckd.co.jp",
    "peilin.lim@appsystems.com.sg",
    "janice-yu@maxell.com.hk",
    "tsuchihashi@samco.co.jp",
    "hemant.waghela@clariant.com",
    "nishant.kamboj@cdil.com",
    "amit.chaudhary@nipponfusso.in",
    "pavankumar@icleantech.com",
    "neeraj@higgsbosonsystems.com",
    "rohit@swift-corp.com",
    "naveen.khurana@nmtronics.com",
    "poonam.bhondve@georgfischer.com",
    "d.suraj@precitec.com",
    "dan.choy@ontoinnovation.com",
    "hadar-p@novami.com",
    "seshadri.s@asmltd.com",
    "tokuriki-h@pack-sd.com",
    "veeresh@maven-silicon.com",
    "Mahesh.kothiyal@xylem.com",
    "chenkueiping@genicgr.com",
    "Tcaldwell@sid.org",
    "svpatil@accurategauging.com",
    "avinash.kumar@elesa-ganter.in",
    "mithilesh.yadav@fabtechnologies.com",
    "support@fluroengg.com",
    "ginumong@morimura.in",
    "nathankb@tpste.com",
    "vanessa.kim@teradyne.com",
    "ops@kloudklick.com",
    "kaipai@hanbell.com",
    "sandip_sen@tii.murugappa.com",
    "deepika_sharma@argconsulting.co.in",
    "apearson@cartencontrols.com",
    "sbp@globetek.in",
    "chitra.parmar@linde.com",
    "accounts@rrpelectronics.com",
    "hshah@rensatubes.com",
    "mahesh@innatera.com",
    "mmeruva@trojantechnologies.com",
    "gauravshah@gampservices.com",
    "accounts1@vasant.in",
    "sarvesh.gunjal@vayusodh.com",
    "paige.tan@thermofisher.com",
    "keshav@vbshilpa.com",
    "akansha@parasartstudio.com",
    "torsten@ptwsingapore.com",
    "operations1.tih@iitr.ac.in",
    "surbhi@jeolindia.com",
    "shivani@ozoneentertainments.com",
    "mohan.selvaraj@esmo-asia.com",
    "sanjay@sahasrasemi.com",
    "kits.esdm@gmail.com",
    "emarketing@sangir.com",
    "deepa.sasidharan@lamresearch.com",
    "INFO@AIMIL.COM",
    "shivasrini@melss.com",
    "kajal.thakur@toshiautomation.com",
    "manish.sharma@interlinks.in",
    "sales@lucidimaging.in",
    "umashankar@aura.co.in",
    "rahul.tyagi@addverb.com",
    "tomoko_suzuki@ha.daifuku.co.jp",
    "angie.cho@pentamaster.com.my",
    "mustaqh.shaik@moschip.com",
    "pritika.koul@smartsocs.com",
    "pradeep@ausdia.com",
    "thejas.raghav@uhptech.com",
    "sanyam.sultania@akribis-sys.com",
    "puneet.gupta@inoxap.com",
    "JAYA.SINGH@PAVILIONSINTERIORS.COM",
    "wassi.uddin@kaynes.org",
    "praveen_kaushik@amat.com",
    "Alimkhan@prime-pci.com",
    "shima.sasaki@us.tel.com",
    "Kannan.Kuriyan@swagelok.com",
    "md@investtn.in",
    "bhupinderduggal@htlaircon.com",
    "industry.cense@iisc.ac.in",
    "tadashi_oowada@ulvac.com",
    "petrinaheng@discosin.com.sg",
    "harshad.umrotkar@growel.com",
    "ifitp.eit@odisha.gov.in",
    "naresh@shavogroup.com",
    "pmishra@yes.tech",
    "scottng@jlk-tech.com"
];

$emailList = [
    'manish.sharma@interlinks.in'
];


$subject = "Important Note for Extra Requirements - SEMICON India 2025";
// $message = "Your email message here.";
// $headers = "From: sender@example.com\r\nReply-To: sender@example.com\r\n";

foreach ($emailList as $email) {
    $email = array($email);
    elastic_mail($subject, $message, $email, 'Important Note for Extra Requirements - SEMICON India 2025');
}